[DO NOT MERGE] Internal command
3mdeb/edk2-platforms pull request #12
Opened 2018-11-09 14:09 UTC by krystian-hebel

Opened a PR for easier comparison of changes, but this should be left as a different branch.

2018-11-09 14:57 UTC, miczyg1 commented
@krystian-hebel wouldn't be the diff better when comparing against `custom_shell_pkg`?

2018-11-09 14:59 UTC, krystian-hebel commented
@miczyg1 I don't think so. Most of these changes were undone, except for the ones in `PlatformPkg.fdf`.

2018-11-09 15:05 UTC, miczyg1 requested changes

2018-11-09 15:05 UTC, miczyg1 commented on Vlv2TbltDevicePkg/PlatformPkg.dec
> +  gTpmDeviceInstanceTpm20PttPtpGuid       = { 0x93d66f66, 0x55da, 0x4f03, { 0x9b, 0x5f, 0x32, 0xcf, 0x9e, 0x54, 0x3b, 0x3a } }
@krystian-hebel could You clean it up please? `git add -p`...

2018-11-09 15:16 UTC, krystian-hebel commented on Vlv2TbltDevicePkg/PlatformPkg.dec
> +  gTpmDeviceInstanceTpm20PttPtpGuid       = { 0x93d66f66, 0x55da, 0x4f03, { 0x9b, 0x5f, 0x32, 0xcf, 0x9e, 0x54, 0x3b, 0x3a } }
@miczyg1 should be fixed now. Editing files that don't follow any standards is painful...

2018-11-09 16:35 UTC, miczyg1 approved these changes

2018-11-13 13:25 UTC, miczyg1 commented
@pietrushnic are You ok with the changes?

2018-11-13 16:42 UTC, pietrushnic approved these changes

2018-11-13 16:47 UTC, miczyg1 commented
Closing PR, since everybody approved.

2018-11-13 16:47 UTC, closed without merging